
services:
  postgresql-server:
    image: bitnami/postgresql:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysupersecretpassword
      POSTGRES_DB: notifications
    networks:
      - microservice-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5

  notifications-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgresql-server:
        condition: service_healthy
    networks:
      - microservice-net
    ports:
      - 8001:8001

volumes:
  postgres_data:


networks:
  microservice-net:
    driver: bridge