apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-app
  namespace: authentication-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-app
  template:
    metadata:
      labels:
        app: authentication-app
    spec:
      containers:
      - name: authentication-app
        image: ${{ secrets.DOCKERHUB_REPO }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: auth-config
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsec
