apiVersion: v1
kind: Service
metadata:
  name: postgresql-authentication-service
  namespace: authentication-app
spec:
  selector:
    app: postgresql-authentication
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
