apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-authentication
  namespace: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-authentication
  template:
    metadata:
      labels:
        app: postgresql-authentication
    spec:
      containers:
      - name: postgresql-authentication
        image: bitnami/postgresql:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: auth-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-authentication-pvc
      volumes:
      - name: postgresql-authentication-pvc
        persistentVolumeClaim:
          claimName: postgresql-authentication-pvc
