name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps: 
      - 
        name: Build the Docker image
        uses: actions/checkout@v4
    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get the current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
      
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: personalirfan/notifications-app-api:latest,personalirfan/notifications-app-api:${{ env.TIMESTAMP }}
          build-args: --pull

      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      -
        name: Update Kubeconfig for AWS EKS
        run: |
          aws eks update-kubeconfig --name notifications-eks-cluster --region ap-south-1
      
      -
        name: Deploy to Kubernetes
        run: |
          ./setup_k8s.sh

      -
        name: Expose the service
        run: |
          kubectl expose deployment notifications-app-api-deployment --type=LoadBalancer --name=notifications-app-api-service

      -
        name: Verify Deployment
        run: |
          kubectl rollout status deployment notifications-app-api-deployment
          kubectl get svc notifications-app-api-service

      -
        name: Link Domain using AWS Route 53
        run: |
          aws route53 change-resource-record-sets --hosted-zone-id Z1234567890 --change-batch file://route53.json
