apiVersion: v1
kind: Service
metadata:
  name: notifications-app-service
  namespace: orchestrator
spec:
  selector:
    app: notifications-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
