apiVersion: v1
kind: Service
metadata:
  name: postgresql-notifications-service
  namespace: orchestrator
spec:
  selector:
    app: postgresql-notifications
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
