apiVersion: v1
kind: Service
metadata:
  name: postgresql-authentication-service
  namespace: orchestrator
spec:
  selector:
    app: postgresql-authentication
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
