# define load balancer rules for our servce

apiVersion: v1
kind: Service
metadata:
  name: notifications-load-balancer-service
spec:
  selector:
    app: notifications-load-balancer-service
  ports:
  - port: 80
    targetPort: 8001
  type: LoadBalancer
