apiVersion: v1
kind: Service
metadata:
  name: notifications-app-service
  namespace: notifications-app
spec:
  selector:
    app: notifications-app
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
