apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: notifications-app
data:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
