apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app
  namespace: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-app
  template:
    metadata:
      labels:
        app: notifications-app
    spec:
      containers:
      - name: notifications-app
        image: notifications-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: notification-config