apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-notifications-pvc
  namespace: orchestrator
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
