apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-notifications
  namespace: notifications-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-notifications
  template:
    metadata:
      labels:
        app: postgresql-notifications
    spec:
      containers:
      - name: postgresql-notifications
        image: bitnami/postgresql:latest
        envFrom:
        - configMapRef:
            name: notification-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-notifications-pvc
      volumes:
      - name: postgresql-notifications-pvc
        persistentVolumeClaim:
          claimName: postgresql-notifications-pvc
