apiVersion: v1
kind: Service
metadata:
  name: postgresql-notifications-service
  namespace: orchestrator
spec:
  selector:
    app: postgresql-notifications
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
